version: '2.2'
services:
  app:
    container_name: realtime_db_app
    environment:
      NODE_ENV: development
    build: .
    volumes:
      - ./:/app
    working_dir: /app
    command: npm run dev
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
